//handling raising an error/exception
try:
	raise nameerror("name error raised!!")
except:
	print("erorrrr")